#!/bin/bash
set -e

# Warn if the DOCKER_HOST socket does not exist
if [[ $DOCKER_HOST == unix://* ]]; then
	socket_file=${DOCKER_HOST#unix://}
	if ! [ -S $socket_file ]; then
		cat >&2 <<-EOT
			ERROR: you need to share your Docker host socket with a volume at $socket_file
			Typically you should run your nginx-proxy with: \`-v /var/run/docker.sock:$socket_file:ro\`
			See the documentation for more details on this error.
		EOT
		socketMissing=1
	fi
fi

# If the user has run the default command
if [ $1 = supervisord ]; then
    # if the socket doesn't exist, fail
    [ "$socketMissing" = 1 ] && exit 1
    # Force regenerator default.conf on startup
    _conf=/etc/nginx/conf.d/default.conf
    [ -f $_conf ] && rm -v $_conf
fi

exec "$@"
